/* 
                        _________________________________
                              (Summative) Assignment
                        ---------------------------------
                                By: Ibrahim Tariq
*/
package grade11summative.tariq;

public class HomeFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HBackground = new javax.swing.JDesktopPane();
        lblHTitle = new javax.swing.JLabel();

        HBackground.setBackground(new java.awt.Color(102, 102, 102));

        lblHTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblHTitle.setForeground(new java.awt.Color(51, 255, 255));
        lblHTitle.setText("<html> This program is made teach about how the lack of quality education is an issue. This program is also made to test your knowledge about the \"Quality Education\" in many different ways so you can self-check your understanding. This program is made to be entertaining as well as informative. Look at the menu bar above to start learning. Press the \"NEXT\" button when you are done.      __________________________________________________     (NOTE: You can only do each Self-Tests once)</html>");

        HBackground.setLayer(lblHTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HBackgroundLayout = new javax.swing.GroupLayout(HBackground);
        HBackground.setLayout(HBackgroundLayout);
        HBackgroundLayout.setHorizontalGroup(
            HBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HBackgroundLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        HBackgroundLayout.setVerticalGroup(
            HBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HBackground)
        );

        setBounds(0, 0, 580, 334);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane HBackground;
    private javax.swing.JLabel lblHTitle;
    // End of variables declaration//GEN-END:variables
}
