/* 
                        _________________________________
                              (Summative) Assignment
                        ---------------------------------
                                By: Ibrahim Tariq
*/
package grade11summative.tariq;

public class MainFrame extends javax.swing.JFrame {

    // Declaration of variables:
    int speed;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        HomeFrame homeFrame = new HomeFrame();
        InternalFrameArea.add(homeFrame);
        homeFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JDesktopPane();
        lblTitle = new javax.swing.JLabel();
        InternalFrameArea = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        homeMenuButton = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenu();
        infoMenuButton = new javax.swing.JMenuItem();
        selfTestMenu = new javax.swing.JMenu();
        matchingMenuButton = new javax.swing.JMenuItem();
        quizMenuButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(204, 204, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 52));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("The Quality Education Goal");

        InternalFrameArea.setBackground(new java.awt.Color(204, 204, 204));
        InternalFrameArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        InternalFrameArea.setPreferredSize(new java.awt.Dimension(580, 334));

        javax.swing.GroupLayout InternalFrameAreaLayout = new javax.swing.GroupLayout(InternalFrameArea);
        InternalFrameArea.setLayout(InternalFrameAreaLayout);
        InternalFrameAreaLayout.setHorizontalGroup(
            InternalFrameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        InternalFrameAreaLayout.setVerticalGroup(
            InternalFrameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        btnNext.setBackground(new java.awt.Color(0, 51, 255));
        btnNext.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnNext.setText("NEXT:");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        Background.setLayer(lblTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Background.setLayer(InternalFrameArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Background.setLayer(btnNext, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(InternalFrameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(InternalFrameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homeMenu.setForeground(new java.awt.Color(0, 0, 102));
        homeMenu.setText("Home");

        homeMenuButton.setForeground(new java.awt.Color(0, 0, 102));
        homeMenuButton.setText("Open");
        homeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuButtonActionPerformed(evt);
            }
        });
        homeMenu.add(homeMenuButton);

        MenuBar.add(homeMenu);

        infoMenu.setForeground(new java.awt.Color(0, 0, 102));
        infoMenu.setText("Information page");

        infoMenuButton.setForeground(new java.awt.Color(0, 0, 102));
        infoMenuButton.setText("Open");
        infoMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuButtonActionPerformed(evt);
            }
        });
        infoMenu.add(infoMenuButton);

        MenuBar.add(infoMenu);

        selfTestMenu.setForeground(new java.awt.Color(0, 0, 102));
        selfTestMenu.setText("Self-Tests");

        matchingMenuButton.setForeground(new java.awt.Color(0, 0, 102));
        matchingMenuButton.setText("Matching");
        matchingMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchingMenuButtonActionPerformed(evt);
            }
        });
        selfTestMenu.add(matchingMenuButton);

        quizMenuButton.setForeground(new java.awt.Color(0, 0, 102));
        quizMenuButton.setText("Quiz");
        quizMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizMenuButtonActionPerformed(evt);
            }
        });
        selfTestMenu.add(quizMenuButton);

        MenuBar.add(selfTestMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background)
        );

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuButtonActionPerformed

        
        // Removes everything from the panal "InternalFrameArea"
        InternalFrameArea.removeAll();
        InternalFrameArea.repaint();
        
        
        
        // Makes Internal frame "HomeFrame" visible:
        HomeFrame home = new HomeFrame();
        InternalFrameArea.add(home);
        home.setVisible(true);

    }//GEN-LAST:event_homeMenuButtonActionPerformed

    private void infoMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuButtonActionPerformed

        // Removes everything from the panal "InternalFrameArea"
        InternalFrameArea.removeAll();
        InternalFrameArea.repaint();
        
        
        
        // Makes Internal frame "InformationFrame" visible:
        InformationFrame information = new InformationFrame();
        InternalFrameArea.add(information);
        information.setVisible(true);

    }//GEN-LAST:event_infoMenuButtonActionPerformed

    private void matchingMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchingMenuButtonActionPerformed

        // Removes everything from the panal "InternalFrameArea"
        InternalFrameArea.removeAll();
        InternalFrameArea.repaint();
        
        
        
        // Makes Internal frame "MatchingFrame" visible:
        MatchingFrame matching  = new MatchingFrame();
        InternalFrameArea.add(matching);
        matching.setVisible(true);

    }//GEN-LAST:event_matchingMenuButtonActionPerformed

    private void quizMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizMenuButtonActionPerformed

        // Removes everything from the panal "InternalFrameArea"
        InternalFrameArea.removeAll();
        InternalFrameArea.repaint();
        
        
        
        // Makes Internal frame "MatchingFrame" visible:
        QuizFrame quiz = new QuizFrame();
        InternalFrameArea.add(quiz);
        quiz.setVisible(true);

    }//GEN-LAST:event_quizMenuButtonActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       
        MainFrame main = new MainFrame();
        main.removeAll();
        main.repaint();
        
        RatingFrame rating = new RatingFrame();
        rating.setVisible(true);
        
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Background;
    private javax.swing.JPanel InternalFrameArea;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnNext;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuItem homeMenuButton;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JMenuItem infoMenuButton;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem matchingMenuButton;
    private javax.swing.JMenuItem quizMenuButton;
    private javax.swing.JMenu selfTestMenu;
    // End of variables declaration//GEN-END:variables
}
