/* 
                        _________________________________
                              (Summative) Assignment
                        ---------------------------------
                                By: Ibrahim Tariq
*/
package grade11summative.tariq;

    // Import statement for MessageBox.
    import static javax.swing.JOptionPane.showMessageDialog;

public class QuizFrame extends javax.swing.JInternalFrame {

    // Declaration of variables:
    int totalQuizMarks = 0;
    int buttonClicked = 0;
    
    /**
     * Creates new form QuizFrame
     */
    public QuizFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuizButtonGroup1 = new javax.swing.ButtonGroup();
        QuizButtonGroup2 = new javax.swing.ButtonGroup();
        QuizButtonGroup3 = new javax.swing.ButtonGroup();
        QuizButtonGroup4 = new javax.swing.ButtonGroup();
        QuizButtonGroup5 = new javax.swing.ButtonGroup();
        QuizButtonGroup6 = new javax.swing.ButtonGroup();
        QBackground = new javax.swing.JDesktopPane();
        lblQTitle = new javax.swing.JLabel();
        lblQuizQuestion1 = new javax.swing.JLabel();
        QuizQuestion1Answer1 = new javax.swing.JRadioButton();
        QuizQuestion1Answer2 = new javax.swing.JRadioButton();
        QuizQuestion1Answer3 = new javax.swing.JRadioButton();
        QuizQuestion1Answer4 = new javax.swing.JRadioButton();
        lblQuizQuestion2 = new javax.swing.JLabel();
        QuizQuestion2Answer1 = new javax.swing.JRadioButton();
        QuizQuestion2Answer2 = new javax.swing.JRadioButton();
        QuizQuestion2Answer3 = new javax.swing.JRadioButton();
        QuizQuestion2Answer4 = new javax.swing.JRadioButton();
        lblQuizQuestion3 = new javax.swing.JLabel();
        QuizQuestion3Answer1 = new javax.swing.JRadioButton();
        QuizQuestion3Answer2 = new javax.swing.JRadioButton();
        QuizQuestion3Answer3 = new javax.swing.JRadioButton();
        QuizQuestion3Answer4 = new javax.swing.JRadioButton();
        lblQuizQuestion4 = new javax.swing.JLabel();
        QuizQuestion4Answer1 = new javax.swing.JRadioButton();
        QuizQuestion4Answer2 = new javax.swing.JRadioButton();
        QuizQuestion4Answer3 = new javax.swing.JRadioButton();
        QuizQuestion4Answer4 = new javax.swing.JRadioButton();
        lblQuizQuestion5 = new javax.swing.JLabel();
        QuizQuestion5Answer1 = new javax.swing.JRadioButton();
        QuizQuestion5Answer2 = new javax.swing.JRadioButton();
        QuizQuestion5Answer3 = new javax.swing.JRadioButton();
        QuizQuestion5Answer4 = new javax.swing.JRadioButton();
        lblQuizQuestion6 = new javax.swing.JLabel();
        QuizQuestion6Answer1 = new javax.swing.JRadioButton();
        QuizQuestion6Answer2 = new javax.swing.JRadioButton();
        QuizQuestion6Answer3 = new javax.swing.JRadioButton();
        QuizQuestion6Answer4 = new javax.swing.JRadioButton();
        btnQuizCalculate = new javax.swing.JButton();

        QBackground.setBackground(new java.awt.Color(102, 102, 102));

        lblQTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQTitle.setForeground(new java.awt.Color(51, 255, 255));
        lblQTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQTitle.setText("Quiz: (5 marks per question)");

        lblQuizQuestion1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion1.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion1.setText("<html>Question 1: The name of UN's Goal 4:<html/>");

        QuizQuestion1Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup1.add(QuizQuestion1Answer1);
        QuizQuestion1Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion1Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion1Answer1.setText("Climate Change");

        QuizQuestion1Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup1.add(QuizQuestion1Answer2);
        QuizQuestion1Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion1Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion1Answer2.setText("Quality Education");

        QuizQuestion1Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup1.add(QuizQuestion1Answer3);
        QuizQuestion1Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion1Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion1Answer3.setText("Education");

        QuizQuestion1Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup1.add(QuizQuestion1Answer4);
        QuizQuestion1Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion1Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion1Answer4.setText("Poverty");

        lblQuizQuestion2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion2.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion2.setText("<html>Question 2: What is UN's Goal 4 about.<html/>");

        QuizQuestion2Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup2.add(QuizQuestion2Answer1);
        QuizQuestion2Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion2Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion2Answer1.setText("Inclusive Education");

        QuizQuestion2Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup2.add(QuizQuestion2Answer2);
        QuizQuestion2Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion2Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion2Answer2.setText("Promoting Lifelong Learning");

        QuizQuestion2Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup2.add(QuizQuestion2Answer3);
        QuizQuestion2Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion2Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion2Answer3.setText("Equitable Education");

        QuizQuestion2Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup2.add(QuizQuestion2Answer4);
        QuizQuestion2Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion2Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion2Answer4.setText("All of the above");

        lblQuizQuestion3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion3.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion3.setText("<html>Question 3: Most current Quality Education goals are due by:<html/>");

        QuizQuestion3Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup3.add(QuizQuestion3Answer1);
        QuizQuestion3Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion3Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion3Answer1.setText("2050");

        QuizQuestion3Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup3.add(QuizQuestion3Answer2);
        QuizQuestion3Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion3Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion3Answer2.setText("2025");

        QuizQuestion3Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup3.add(QuizQuestion3Answer3);
        QuizQuestion3Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion3Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion3Answer3.setText("2045");

        QuizQuestion3Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup3.add(QuizQuestion3Answer4);
        QuizQuestion3Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion3Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion3Answer4.setText("None of the above");

        lblQuizQuestion4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion4.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion4.setText("<html>Question 4: When were the 17 SDG's first put in place.<html/>");

        QuizQuestion4Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup4.add(QuizQuestion4Answer1);
        QuizQuestion4Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion4Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion4Answer1.setText("2015");

        QuizQuestion4Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup4.add(QuizQuestion4Answer2);
        QuizQuestion4Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion4Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion4Answer2.setText("1995");

        QuizQuestion4Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup4.add(QuizQuestion4Answer3);
        QuizQuestion4Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion4Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion4Answer3.setText("2010");

        QuizQuestion4Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup4.add(QuizQuestion4Answer4);
        QuizQuestion4Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion4Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion4Answer4.setText("None of the above");

        lblQuizQuestion5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion5.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion5.setText("<html>Question 5: When was the action plan Agenda 21 created.<html/>");

        QuizQuestion5Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup5.add(QuizQuestion5Answer1);
        QuizQuestion5Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion5Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion5Answer1.setText("1978");

        QuizQuestion5Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup5.add(QuizQuestion5Answer2);
        QuizQuestion5Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion5Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion5Answer2.setText("1992");

        QuizQuestion5Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup5.add(QuizQuestion5Answer3);
        QuizQuestion5Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion5Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion5Answer3.setText("2020");

        QuizQuestion5Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup5.add(QuizQuestion5Answer4);
        QuizQuestion5Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion5Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion5Answer4.setText("None of the above");

        lblQuizQuestion6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblQuizQuestion6.setForeground(new java.awt.Color(51, 255, 255));
        lblQuizQuestion6.setText("<html>Question 6: How many countres adopted Agenda 21.<html/>");

        QuizQuestion6Answer1.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup6.add(QuizQuestion6Answer1);
        QuizQuestion6Answer1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion6Answer1.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion6Answer1.setText("243");

        QuizQuestion6Answer2.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup6.add(QuizQuestion6Answer2);
        QuizQuestion6Answer2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion6Answer2.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion6Answer2.setText("93");

        QuizQuestion6Answer3.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup6.add(QuizQuestion6Answer3);
        QuizQuestion6Answer3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion6Answer3.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion6Answer3.setText("178");

        QuizQuestion6Answer4.setBackground(new java.awt.Color(102, 102, 102));
        QuizButtonGroup6.add(QuizQuestion6Answer4);
        QuizQuestion6Answer4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        QuizQuestion6Answer4.setForeground(new java.awt.Color(51, 255, 255));
        QuizQuestion6Answer4.setText("159");

        btnQuizCalculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQuizCalculate.setText("Calculate Mark");
        btnQuizCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizCalculateActionPerformed(evt);
            }
        });

        QBackground.setLayer(lblQTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion1Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion1Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion1Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion1Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion2Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion2Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion2Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion2Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion3Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion3Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion3Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion3Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion4Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion4Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion4Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion4Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion5Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion5Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion5Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion5Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(lblQuizQuestion6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion6Answer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion6Answer2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion6Answer3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(QuizQuestion6Answer4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QBackground.setLayer(btnQuizCalculate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout QBackgroundLayout = new javax.swing.GroupLayout(QBackground);
        QBackground.setLayout(QBackgroundLayout);
        QBackgroundLayout.setHorizontalGroup(
            QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addComponent(lblQTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuizCalculate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuizQuestion1Answer1)
                            .addComponent(QuizQuestion1Answer2)
                            .addComponent(QuizQuestion1Answer3)
                            .addComponent(QuizQuestion1Answer4)
                            .addComponent(lblQuizQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(QBackgroundLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(QuizQuestion2Answer1)
                                            .addComponent(QuizQuestion2Answer2)
                                            .addComponent(QuizQuestion2Answer4)
                                            .addComponent(QuizQuestion2Answer3)))
                                    .addGroup(QBackgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(QuizQuestion5Answer4)
                                            .addComponent(QuizQuestion5Answer1)
                                            .addComponent(QuizQuestion5Answer2)
                                            .addComponent(QuizQuestion5Answer3)
                                            .addComponent(lblQuizQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuizQuestion3Answer1)
                                    .addComponent(QuizQuestion3Answer2)
                                    .addComponent(QuizQuestion3Answer3)
                                    .addComponent(QuizQuestion3Answer4)
                                    .addComponent(lblQuizQuestion6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuizQuestion6Answer1)
                                    .addComponent(QuizQuestion6Answer2)
                                    .addComponent(QuizQuestion6Answer3)
                                    .addComponent(QuizQuestion6Answer4))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQuizQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQuizQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuizQuestion4Answer3)
                            .addComponent(QuizQuestion4Answer2)
                            .addComponent(QuizQuestion4Answer1)
                            .addComponent(QuizQuestion4Answer4)
                            .addComponent(lblQuizQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        QBackgroundLayout.setVerticalGroup(
            QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QBackgroundLayout.createSequentialGroup()
                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuizCalculate))
                .addGap(5, 5, 5)
                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuizQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuizQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuizQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addComponent(QuizQuestion1Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion1Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion1Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion1Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addComponent(QuizQuestion2Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion2Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion2Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion2Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(QuizQuestion3Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion3Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion3Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion3Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(QBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addComponent(lblQuizQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion4Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion4Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion4Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion4Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QBackgroundLayout.createSequentialGroup()
                                .addComponent(lblQuizQuestion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion6Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion6Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion6Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuizQuestion6Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(QBackgroundLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblQuizQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion5Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion5Answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion5Answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuizQuestion5Answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QBackground)
        );

        setBounds(0, 0, 580, 334);
    }// </editor-fold>//GEN-END:initComponents

    public String AnswersQuiz(int score,int total) {
        
        // Declaration of variables and array: (Inside the method only)
        int quizMark = score;
        double mark = ((score * 100)/total);
        String matchAnswer;
        String [] comments = {"You got a perfect score!!","Great job almost a perfect score!!",
        "Not bad.","Good job but there is still space for inprovement.", "You barely passed the self test.",
        "Sorry you failed better luck next time."};
        
        
        // This "If,Than,Else" is for the types of comment that is given based on the user's mark percent:
        if ( mark == 100){
            matchAnswer = (comments[0] + " \n Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        else if (mark >= 90){
            matchAnswer = (comments[1] + " \n Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        else if (mark >= 75){
            matchAnswer = (comments[2] + " \n Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        else if (mark >= 60){
            matchAnswer = (comments[3] + " \n Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        else if (mark >= 50){
            matchAnswer = (comments[4] + " Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        else{
            matchAnswer = (comments[5] + " Your 'Quiz' mark is: " + quizMark + "/" + total);        
        }
        // Return the reply that contains the comment and mark:
        return matchAnswer;
    }
    
    // When the "Calculate Mark" button is pressed:
    private void btnQuizCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizCalculateActionPerformed
        
        // Loop so the user can only enter the marks only once:
        while (buttonClicked < 1) {
            
            // Counter for the number of times the button is clicked:
            buttonClicked =  buttonClicked + 1;
            
            // If the right answer for question 1 is selected:
            if (QuizQuestion1Answer2.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
            // If the right answer for question 2 is selected:
            if (QuizQuestion2Answer4.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
            // If the right answer for question 3 is selected:
            if (QuizQuestion3Answer4.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
            // If the right answer for question 4 is selected:
            if (QuizQuestion4Answer1.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
            // If the right answer for question 5 is selected:
            if (QuizQuestion5Answer2.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
            // If the right answer for question 6 is selected:
            if (QuizQuestion6Answer3.isSelected())
            {
                // Counter for user's mark:
                totalQuizMarks += 5;
            }
        }
        
        // Show reply in a message box:
        showMessageDialog(this,AnswersQuiz(totalQuizMarks,30));
        
    }//GEN-LAST:event_btnQuizCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane QBackground;
    private javax.swing.ButtonGroup QuizButtonGroup1;
    private javax.swing.ButtonGroup QuizButtonGroup2;
    private javax.swing.ButtonGroup QuizButtonGroup3;
    private javax.swing.ButtonGroup QuizButtonGroup4;
    private javax.swing.ButtonGroup QuizButtonGroup5;
    private javax.swing.ButtonGroup QuizButtonGroup6;
    private javax.swing.JRadioButton QuizQuestion1Answer1;
    private javax.swing.JRadioButton QuizQuestion1Answer2;
    private javax.swing.JRadioButton QuizQuestion1Answer3;
    private javax.swing.JRadioButton QuizQuestion1Answer4;
    private javax.swing.JRadioButton QuizQuestion2Answer1;
    private javax.swing.JRadioButton QuizQuestion2Answer2;
    private javax.swing.JRadioButton QuizQuestion2Answer3;
    private javax.swing.JRadioButton QuizQuestion2Answer4;
    private javax.swing.JRadioButton QuizQuestion3Answer1;
    private javax.swing.JRadioButton QuizQuestion3Answer2;
    private javax.swing.JRadioButton QuizQuestion3Answer3;
    private javax.swing.JRadioButton QuizQuestion3Answer4;
    private javax.swing.JRadioButton QuizQuestion4Answer1;
    private javax.swing.JRadioButton QuizQuestion4Answer2;
    private javax.swing.JRadioButton QuizQuestion4Answer3;
    private javax.swing.JRadioButton QuizQuestion4Answer4;
    private javax.swing.JRadioButton QuizQuestion5Answer1;
    private javax.swing.JRadioButton QuizQuestion5Answer2;
    private javax.swing.JRadioButton QuizQuestion5Answer3;
    private javax.swing.JRadioButton QuizQuestion5Answer4;
    private javax.swing.JRadioButton QuizQuestion6Answer1;
    private javax.swing.JRadioButton QuizQuestion6Answer2;
    private javax.swing.JRadioButton QuizQuestion6Answer3;
    private javax.swing.JRadioButton QuizQuestion6Answer4;
    private javax.swing.JButton btnQuizCalculate;
    private javax.swing.JLabel lblQTitle;
    private javax.swing.JLabel lblQuizQuestion1;
    private javax.swing.JLabel lblQuizQuestion2;
    private javax.swing.JLabel lblQuizQuestion3;
    private javax.swing.JLabel lblQuizQuestion4;
    private javax.swing.JLabel lblQuizQuestion5;
    private javax.swing.JLabel lblQuizQuestion6;
    // End of variables declaration//GEN-END:variables
}
